# ARRAYS

In [2]:
import array as arr
a=arr.array('i',[1,2,3]) # creating array
print(a)

array('i', [1, 2, 3])


In [3]:
print(len(a)) # finding length of array

3


In [4]:
a.append(7) # appending element into array
print(a)

array('i', [1, 2, 3, 7])


In [6]:
a.extend([5,6,4]) # extending the array
print(a)

array('i', [1, 2, 3, 7, 5, 6, 4])


In [10]:
a.insert(2,8) # inserting the element in array at particular position
print(a)

array('i', [8, 1, 8, 2, 3, 7, 5, 6, 4, 8])


In [12]:
b=arr.array("i",[11,12,13]) # array concatination
print(a+b)

array('i', [8, 1, 8, 2, 3, 7, 5, 6, 4, 8, 11, 12, 13])


In [14]:
c=arr.array("i",[45,46,47])
print(c)

array('i', [45, 46, 47])


In [15]:
print(a+b+c) # concatinatio

array('i', [8, 1, 8, 2, 3, 7, 5, 6, 4, 8, 11, 12, 13, 45, 46, 47])


In [17]:
print(a.remove(4))

None


In [19]:
a.remove(6) # removing the element from array
print(a)

array('i', [8, 1, 8, 2, 3, 7, 5, 8])


In [20]:
a.pop(2) # popping the element from array
print(a)

array('i', [8, 1, 2, 3, 7, 5, 8])


In [21]:
a[0:6] # slicing operator
print(a)

array('i', [8, 1, 2, 3, 7, 5, 8])


In [22]:
a[0:3]

array('i', [8, 1, 2])

In [23]:
x=len(a)
print(x)

7


In [25]:
a[0:x]

array('i', [8, 1, 2, 3, 7, 5, 8])

In [26]:
a[1:4]

array('i', [1, 2, 3])

In [28]:
for i in a:
    print(i,end=',')

8,1,2,3,7,5,8,

# NUMPY

import numpy as np
n=np.array([1,2,3]) # crating array
print(n)

In [40]:
m=np.array([(4,5,6),(7,8,9)]) # creating 2dim array
print(m)

[[4 5 6]
 [7 8 9]]


In [41]:
p=np.array([(3,4,5),(7,8,9),(1,4,5)]) 
print(p)

[[3 4 5]
 [7 8 9]
 [1 4 5]]


In [43]:
print(p.ndim)
print(m.ndim)

2
2


In [44]:
print(m.itemsize) # finding item size

4


In [46]:
print(m.dtype) # finding data type

int32


In [47]:
print(p.shape) # finding shape of array

(3, 3)


In [49]:
m=m.reshape(3,2) # changing shape of array
print(m)

[[4 5]
 [6 7]
 [8 9]]


In [51]:
print(m[2,1]) # slicing operator

9


In [55]:
l=np.array([(0,1),(2,3),(4,5)]) # slicing operator
print(l[0:3,1])

[1 3 5]


In [57]:
print(l[0:,0]) # slicing operator

[0 2 4]


In [59]:
r=np.linspace(2,4,7)
print(r)

[2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.        ]


In [60]:
w=np.array([4,3,7]) # to find min,max,sum of array
print(max(w))
print(min(w))
print(sum(w))

7
3
14


In [17]:
import numpy as np
i=np.array([(5,3,7),(7,1,2),(6,9,4)])  # finding sum of colums and rows using sum of axis
print(i.sum(axis=1))
print(i.sum(axis=0))

[15 10 19]
[18 13 13]


In [20]:
print(np.sqrt(i)) #srure root and divison
print(np.std(i))

[[2.23606798 1.73205081 2.64575131]
 [2.64575131 1.         1.41421356]
 [2.44948974 3.         2.        ]]
2.469567863432541


In [27]:
import numpy as np
j=np.array([(5,3,7),(7,1,2),(6,9,4)]) # arithmatic operators
print("addition",i+j)
print("subtraction",i-j)
print("multiplication",i*j)
print("divison",i/j)

addition [[10  6 14]
 [14  2  4]
 [12 18  8]]
subtraction [[0 0 0]
 [0 0 0]
 [0 0 0]]
multiplication [[25  9 49]
 [49  1  4]
 [36 81 16]]
divison [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [29]:
print(np.vstack((i,j)))  # to find hstack and vstack
print(np.hstack((i,j)))

[[5 3 7]
 [7 1 2]
 [6 9 4]
 [5 3 7]
 [7 1 2]
 [6 9 4]]
[[5 3 7 5 3 7]
 [7 1 2 7 1 2]
 [6 9 4 6 9 4]]


In [31]:
print(i.ravel()) # raveling

[5 3 7 7 1 2 6 9 4]
